/**
 * Enhanced Report PDF Export
 * 
 * Generates professional PDF reports with two layout styles using html2pdf on the frontend.
 * This complements the existing ReportLab backend implementation.
 */

import { Report, ReportSection } from '@/types';
import { LayoutStyle, getLayoutCSS, getLayoutContainerClass, MODERN_LAYOUT_CSS, MINIMAL_LAYOUT_CSS } from './report-layout-styles';

type PDFTable = {
  title: string;
  columns: string[];
  rows: string[][];
};

function collectReportTables(report: Report): PDFTable[] {
  const tables: PDFTable[] = [];

  report.sections.forEach((section) => {
    if (section.type !== 'table' || !section.data || section.data.length === 0) {
      return;
    }
    const columns = section.columns && section.columns.length > 0
      ? section.columns
      : Object.keys(section.data[0] || {});
    const rows = section.data.map((row) => columns.map((col) => String(row[col] ?? '-')));
    tables.push({
      title: section.title || 'Detailed Data',
      columns,
      rows,
    });
  });

  if (tables.length === 0 && report.rawData && report.rawData.length > 0) {
    const columns = report.columns && report.columns.length > 0
      ? report.columns
      : Object.keys(report.rawData[0] || {});
    const rows = report.rawData.map((row) => columns.map((col) => String(row[col] ?? '-')));
    tables.push({
      title: 'Detailed Data',
      columns,
      rows,
    });
  }

  return tables;
}

async function buildPdfWithJsPdf(report: Report): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const autoTableModule = await import('jspdf-autotable');
  const autoTable = autoTableModule.default;

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4',
    compress: true,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 28;
  let cursorY = 36;

  doc.setFontSize(16);
  doc.text(report.title || 'Report', margin, cursorY);
  cursorY += 16;

  if (report.description) {
    doc.setFontSize(10);
    const descriptionLines = doc.splitTextToSize(report.description, pageWidth - margin * 2);
    doc.text(descriptionLines, margin, cursorY);
    cursorY += descriptionLines.length * 12 + 6;
  }

  const metadataRows = [
    ['Report Type', report.reportType.replace(/_/g, ' ')],
    ['Generated', new Date(report.createdAt).toLocaleString()],
    ['Database', report.metadata?.database || ''],
    ['Generated By', report.metadata?.generatedBy || 'System'],
    ['Records', String(report.rowCount || report.rawData?.length || 0)],
    ['Query Time (s)', String(report.executionTime || 0)],
    ['SQL Query', report.sql || ''],
  ];

  autoTable(doc, {
    startY: cursorY,
    head: [['Metadata', 'Value']],
    body: metadataRows,
    theme: 'grid',
    styles: {
      fontSize: 8,
      overflow: 'linebreak',
      cellPadding: 4,
      valign: 'top',
    },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 120 },
      1: { cellWidth: 'auto' },
    },
    margin: { left: margin, right: margin },
  });

  cursorY = ((doc as any).lastAutoTable?.finalY || cursorY) + 14;

  const tables = collectReportTables(report);
  for (const table of tables) {
    if (cursorY > doc.internal.pageSize.getHeight() - 80) {
      doc.addPage();
      cursorY = 36;
    }

    doc.setFontSize(12);
    doc.text(`${table.title} (${table.rows.length} rows)`, margin, cursorY);
    cursorY += 8;

    autoTable(doc, {
      startY: cursorY,
      head: [table.columns],
      body: table.rows,
      theme: 'grid',
      styles: {
        fontSize: 7,
        overflow: 'linebreak',
        cellPadding: 3,
        valign: 'top',
      },
      headStyles: {
        fillColor: [52, 73, 94],
        textColor: 255,
        fontStyle: 'bold',
      },
      margin: { left: margin, right: margin },
      didDrawPage: (hookData) => {
        doc.setFontSize(8);
        doc.text(
          `Page ${hookData.pageNumber}`,
          pageWidth - margin - 40,
          doc.internal.pageSize.getHeight() - 12
        );
      },
    });

    cursorY = ((doc as any).lastAutoTable?.finalY || cursorY) + 12;
  }

  return doc.output('blob');
}

async function buildPdfWithHtml2PdfFallback(report: Report, layout: LayoutStyle): Promise<Blob> {
  const html2pdf = (await import('html2pdf.js')).default;

  let container: HTMLDivElement | null = null;
  try {
    container = document.createElement('div');
    container.innerHTML = generateReportHTML(report, layout);
    container.style.position = 'fixed';
    container.style.left = '-100000px';
    container.style.top = '0';
    container.style.width = '1400px';
    container.style.zIndex = '-1';
    container.style.background = '#fff';
    document.body.appendChild(container);

    await new Promise((resolve) => requestAnimationFrame(() => resolve(null)));
    await new Promise((resolve) => setTimeout(resolve, 50));

    const options = {
      margin: [10, 8, 10, 8],
      image: { type: 'jpeg', quality: 0.95 },
      html2canvas: {
        scale: 1.2,
        letterSpacing: '0px',
        useCORS: true,
        allowTaint: true,
      },
      jsPDF: {
        orientation: 'landscape',
        precision: 10,
        unit: 'mm',
        format: 'a4',
      },
      pagebreak: {
        mode: ['css', 'legacy'],
        avoid: ['tr', '.pdf-avoid-break'],
      },
      logging: false,
      autoPaging: true,
    };

    const blob = await new Promise<Blob>((resolve, reject) => {
      html2pdf()
        .set(options)
        .from(container)
        .toPdf()
        .output('blob')
        .then((resultBlob: Blob) => resolve(resultBlob))
        .catch((err: { message?: string }) => reject(new Error(`PDF generation failed: ${err?.message || 'Unknown error'}`)));
    });

    return blob;
  } finally {
    if (container && document.body.contains(container)) {
      document.body.removeChild(container);
    }
  }
}

/**
 * Generates HTML string for a report with specified layout
 * Includes ALL records and ALL columns (no truncation)
 */
export function generateReportHTML(report: Report, layout: LayoutStyle = 'modern'): string {
  const reportDate = new Date(report.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const containerClass = getLayoutContainerClass(layout);
  const css = getLayoutCSS(layout);

  const sectionsHTML = buildSectionsHTML(report, layout);

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>${report.title}</title>
        <style>
          ${css}
          
          /* PDF-specific overrides for proper fitting */
          body {
            margin: 0;
            padding: 0;
            page-break-after: avoid;
          }
          
          .modern-container, .minimal-container {
            max-width: 100%;
            margin: 0;
            padding: 20px;
            page-break-after: avoid;
          }
          
          table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            page-break-inside: avoid;
          }
          
          table.data-table th, table.data-table td {
            padding: 8px;
            text-align: left;
            word-wrap: break-word;
            word-break: break-word;
          }
          
          table.data-table thead {
            page-break-after: avoid;
          }
          
          table.data-table tr {
            page-break-inside: avoid;
          }
        </style>
      </head>
      <body>
        <div class="${containerClass}">
          ${renderHeader(report, reportDate, layout)}
          ${renderMetadataBlock(report)}
          ${sectionsHTML}
          ${renderFooter(report, layout)}
        </div>
      </body>
    </html>
  `;

  return html;
}

function buildSectionsHTML(report: Report, layout: LayoutStyle): string {
  const sections = report.sections && report.sections.length > 0
    ? report.sections
    : report.rawData && report.rawData.length > 0
      ? [{
          id: 'fallback-table',
          title: 'Detailed Data',
          description: 'Complete dataset from the query',
          type: 'table' as const,
          data: report.rawData,
          columns: report.columns || Object.keys(report.rawData[0] || {}),
        }]
      : [];

  return sections
    .map((section) => renderSection(section, layout))
    .join('');
}

function renderMetadataBlock(report: Report): string {
  const metadataRows = [
    ['Report Type', report.reportType.replace(/_/g, ' ').toUpperCase()],
    ['Database', report.metadata.database],
    ['Generated By', report.metadata.generatedBy || 'System'],
    ['Total Records', String(report.rowCount || report.rawData?.length || 0)],
    ['SQL Query', report.sql || ''],
  ];

  return `
    <div class="report-section pdf-avoid-break">
      <div class="section-header">
        <h2 class="section-title">Report Metadata</h2>
        <p class="section-description">Summary details included in the exported file</p>
      </div>
      <div class="section-content">
        <table class="data-table">
          <tbody>
            ${metadataRows
              .map(
                ([label, value]) => `
                  <tr>
                    <th style="width: 180px; white-space: normal; word-break: break-word;">${escapeHtml(label)}</th>
                    <td style="white-space: normal; word-break: break-word;">${escapeHtml(String(value ?? ''))}</td>
                  </tr>
                `
              )
              .join('')}
          </tbody>
        </table>
      </div>
    </div>
  `;
}

/**
 * Renders the report header section
 */
function renderHeader(report: Report, reportDate: string, layout: LayoutStyle): string {
  const layoutClass = layout === 'modern' ? 'report-header' : 'report-header';
  
  return `
    <div class="${layoutClass}">
      <h1 class="report-title">${escapeHtml(report.title)}</h1>
      ${report.description ? `<p class="report-subtitle">${escapeHtml(report.description)}</p>` : ''}
      <div class="report-meta">
        <div class="meta-item">
          <span class="meta-label">Generated:</span> ${reportDate}
        </div>
        <div class="meta-item">
          <span class="meta-label">Database:</span> ${escapeHtml(report.metadata.database)}
        </div>
        <div class="meta-item">
          <span class="meta-label">Records:</span> ${report.rowCount || 0}
        </div>
        ${report.executionTime ? `
        <div class="meta-item">
          <span class="meta-label">Query Time:</span> ${report.executionTime.toFixed(2)}s
        </div>
        ` : ''}
      </div>
    </div>
  `;
}

/**
 * Renders a single report section with ALL data (no truncation)
 */
function renderSection(section: ReportSection, layout: LayoutStyle): string {
  let content = '';

  // Render metrics
  if (section.type === 'metrics' && section.metrics) {
    content = renderMetrics(section.metrics, layout);
  }

  // Render table - INCLUDE ALL DATA, ALL COLUMNS
  if (section.type === 'table' && section.data && section.data.length > 0) {
    content = renderTable(section.columns || [], section.data, layout); // No slicing - include all
  }

  // Render summary/insights
  if (section.type === 'summary' && section.summary) {
    content = `
      <div class="summary-box">
        ${escapeHtml(section.summary).replace(/\n/g, '<br />')}
      </div>
    `;
  }

  // Render chart placeholder
  if ((section.type === 'chart' || section.type === 'visualization') && section.chartConfig) {
    content = `
      <div class="chart-container">
        Chart: ${escapeHtml(section.chartConfig.type || 'Chart')} visualization
        <br />(Export to PDF to view)
      </div>
    `;
  }

  if (!content) {
    return '';
  }

  const sectionClass = layout === 'modern' ? 'report-section' : 'report-section';

  return `
    <div class="${sectionClass}">
      <div class="section-header">
        <h2 class="section-title">${escapeHtml(section.title)}</h2>
        ${section.description ? `<p class="section-description">${escapeHtml(section.description)}</p>` : ''}
      </div>
      <div class="section-content">
        ${content}
      </div>
    </div>
  `;
}

/**
 * Renders metrics section
 */
function renderMetrics(metrics: ReportSection['metrics'], layout: LayoutStyle): string {
  if (!metrics || metrics.length === 0) return '';

  if (layout === 'modern') {
    return `
      <div class="metrics-grid">
        ${metrics
          .map(
            (metric) => `
          <div class="metric-card">
            <div class="metric-label">${escapeHtml(metric.label)}</div>
            <div class="metric-value">${escapeHtml(String(metric.value))}</div>
            ${
              metric.trend && metric.trendValue
                ? `<div class="metric-trend ${metric.trend === 'up' ? 'positive' : metric.trend === 'down' ? 'negative' : ''}">
                  ${metric.trend === 'up' ? '↑' : metric.trend === 'down' ? '↓' : '→'} ${Math.abs(metric.trendValue)}%
                </div>`
                : ''
            }
          </div>
        `
          )
          .join('')}
      </div>
    `;
  } else {
    // Minimal layout - table format
    return `
      <table class="metrics-grid">
        ${metrics
          .map(
            (metric) => `
          <tr class="metric-card">
            <td class="metric-label">${escapeHtml(metric.label)}</td>
            <td class="metric-value">${escapeHtml(String(metric.value))}</td>
            <td class="metric-trend">
              ${
                metric.trend && metric.trendValue
                  ? `${metric.trend === 'up' ? '↑' : metric.trend === 'down' ? '↓' : '→'} ${Math.abs(metric.trendValue)}%`
                  : 'No change'
              }
            </td>
          </tr>
        `
          )
          .join('')}
      </table>
    `;
  }
}

/**
 * Renders a data table with ALL columns and ALL rows (no truncation)
 */
function renderTable(columns: string[], data: Record<string, unknown>[], layout: LayoutStyle): string {
  if (!columns || columns.length === 0 || !data || data.length === 0) {
    return '';
  }

  const displayColumns = columns;
  const chunkSize = 35;

  const renderRows = (rows: Record<string, unknown>[]) => rows
    .map(
      (row) => `
        <tr>
          ${displayColumns
            .map((col) => `<td style="white-space: normal; word-break: break-word; vertical-align: top;">${escapeHtml(String(row[col] ?? '-'))}</td>`)
            .join('')}
        </tr>
      `
    )
    .join('');

  const chunks: string[] = [];
  for (let start = 0; start < data.length; start += chunkSize) {
    const chunk = data.slice(start, start + chunkSize);
    const headersHTML = displayColumns
      .map((col) => `<th style="white-space: normal; word-break: break-word;">${escapeHtml(col)}</th>`)
      .join('');

    chunks.push(`
      <div class="pdf-avoid-break" style="margin-bottom: 16px;">
        <table class="data-table">
          <thead>
            <tr>${headersHTML}</tr>
          </thead>
          <tbody>
            ${renderRows(chunk)}
          </tbody>
        </table>
        <p style="font-size: 11px; margin-top: 8px; color: #666; page-break-inside: avoid;">Rows ${start + 1}-${Math.min(start + chunkSize, data.length)} of ${data.length} | Columns: ${columns.length}</p>
      </div>
    `);
  }

  return chunks.join('');
}

/**
 * Renders the report footer
 */
function renderFooter(report: Report, layout: LayoutStyle): string {
  return `
    <div class="report-footer">
      <p>This report was automatically generated by Talk2SQL Analytics System</p>
      <p style="margin-top: 5px;">© ${new Date().getFullYear()} All rights reserved</p>
    </div>
  `;
}

/**
 * Escapes HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Exports report to PDF using html2pdf library
 * Make sure to include html2pdf in your package.json
 */
export async function exportReportToPDF(
  report: Report,
  layout: LayoutStyle = 'modern'
): Promise<void> {
  try {
    const blob = await generateReportPDFBlob(report, layout);
    const filename = `${report.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`;
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    anchor.click();
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('PDF export error:', error);
    throw new Error('Failed to export PDF.');
  }
}

/**
 * Generates a PDF as Blob (for saving or sending)
 */
export async function generateReportPDFBlob(
  report: Report,
  layout: LayoutStyle = 'modern'
): Promise<Blob> {
  try {
    try {
      return await buildPdfWithJsPdf(report);
    } catch (primaryError) {
      console.warn('jsPDF path failed; using html2pdf fallback', primaryError);
      return await buildPdfWithHtml2PdfFallback(report, layout);
    }
  } catch (error) {
    console.error('PDF blob generation error:', error);
    throw error;
  }
}
